from functions.ackley import ackley
from functions.easoms import easom
from functions.gp import goldstein_price

GA_PARAMS = {
    "ackley_fast": {
        "function": ackley,
        "population_size": 50,
        "chromosome_len": 24,
        "max_epochs": 100,
        "n_elites": 1,
        "mut_prob": 0.02,
        "bounds": [(-32.768, 32.768), (-32.768, 32.768)],
    },
    "ackley_standard": {
        "function": ackley,
        "population_size": 150,
        "chromosome_len": 32,
        "max_epochs": 250,
        "n_elites": 2,
        "mut_prob": 0.05,
        "bounds": [(-32.768, 32.768), (-32.768, 32.768)],
    },
    "ackley_robust": {
        "function": ackley,
        "population_size": 300,
        "chromosome_len": 40,
        "max_epochs": 500,
        "n_elites": 5,
        "mut_prob": 0.1,
        "bounds": [(-32.768, 32.768), (-32.768, 32.768)],
    },
    "goldstein_fast": {
        "function": goldstein_price,
        "population_size": 100,
        "chromosome_len": 30,
        "max_epochs": 150,
        "n_elites": 2,
        "mut_prob": 0.01,
        "bounds": [(-2.0, 2.0), (-2.0, 2.0)],
    },
    "goldstein_standard": {
        "function": goldstein_price,
        "population_size": 250,
        "chromosome_len": 40,
        "max_epochs": 300,
        "n_elites": 5,
        "mut_prob": 0.02,
        "bounds": [(-2.0, 2.0), (-2.0, 2.0)],
    },
    "goldstein_robust": {
        "function": goldstein_price,
        "population_size": 500,
        "chromosome_len": 60,
        "max_epochs": 600,
        "n_elites": 10,
        "mut_prob": 0.05,
        "bounds": [(-2.0, 2.0), (-2.0, 2.0)],
    },
    "easom_fast": {
        "function": easom,
        "population_size": 200,
        "chromosome_len": 32,
        "max_epochs": 200,
        "n_elites": 1,
        "mut_prob": 0.05,
        "bounds": [(-100.0, 100.0), (-100.0, 100.0)],
    },
    "easom_standard": {
        "function": easom,
        "population_size": 600,
        "chromosome_len": 32,
        "max_epochs": 500,
        "n_elites": 2,
        "mut_prob": 0.1,
        "bounds": [(-100.0, 100.0), (-100.0, 100.0)],
    },
    "easom_robust": {
        "function": easom,
        "population_size": 1500,
        "chromosome_len": 40,
        "max_epochs": 1000,
        "n_elites": 2,
        "mut_prob": 0.2,
        "bounds": [(-100.0, 100.0), (-100.0, 100.0)],
    },
}
